package com.yjjr.yjfutures.contants;

/**
 * Created by Administrator on 2015/6/2.
 */
public interface Constants {

    String CONTENT_PARAMETER = "CONTENT_PARAMETER";
    String CONTENT_PARAMETER_2 = "CONTENT_PARAMETER_2";
    String CONTENT_PARAMETER_3 = "CONTENT_PARAMETER_3";
    String CONTENT_PARAMETER_4 = "CONTENT_PARAMETER_4";
    String CONTENT_PARAMETER_5 = "CONTENT_PARAMETER_5";
    String CONTENT_PARAMETER_6 = "CONTENT_PARAMETER_6";
    String CONTENT_PARAMETER_7 = "CONTENT_PARAMETER_7";
    String CONTENT_PARAMETER_8 = "CONTENT_PARAMETER_8";
    String CONTENT_PARAMETER_9 = "CONTENT_PARAMETER_9";
    String CONTENT_PARAMETER_10 = "CONTENT_PARAMETER_10";
    String CONTENT_PARAMETER_11 = "CONTENT_PARAMETER_11";
    String CONTENT_PARAMETER_12 = "CONTENT_PARAMETER_12";
    String CONTENT_PARAMETER_13 = "CONTENT_PARAMETER_13";
    String CONTENT_PARAMETER_TOTAL_PAGE = "CONTENT_PARAMETER_TOTAL_PAGE";

}
